import type { BracketConfig } from './index'

export const sample: BracketConfig = {
  type: 'fs:bracket',
  fixtures: [
    {
      id: 'sample-ucl-qf1-leg1',
      competition_slug: 'ucl',
      season: '2025',
      matchday: null,
      stage: 'quarter-final',
      phase: 'knockout',
      kickoff_at: '2026-04-08T19:00:00Z',
      status: 'finished',
      home_score: 2,
      away_score: 1,
      home_team_name: 'Arsenal',
      away_team_name: 'Real Madrid',
      home: { id: 'arsenal', slug: 'arsenal', name: 'Arsenal', crest_url: null },
      away: {
        id: 'real-madrid',
        slug: 'real-madrid',
        name: 'Real Madrid',
        crest_url: null,
      },
    },
    {
      id: 'sample-ucl-qf1-leg2',
      competition_slug: 'ucl',
      season: '2025',
      matchday: null,
      stage: 'quarter-final',
      phase: 'knockout',
      kickoff_at: '2026-04-15T19:00:00Z',
      status: 'finished',
      home_score: 1,
      away_score: 2,
      home_team_name: 'Real Madrid',
      away_team_name: 'Arsenal',
      home: {
        id: 'real-madrid',
        slug: 'real-madrid',
        name: 'Real Madrid',
        crest_url: null,
      },
      away: { id: 'arsenal', slug: 'arsenal', name: 'Arsenal', crest_url: null },
    },
    {
      id: 'sample-ucl-sf1',
      competition_slug: 'ucl',
      season: '2025',
      matchday: null,
      stage: 'semi-final',
      phase: 'knockout',
      kickoff_at: '2026-05-01T19:00:00Z',
      status: 'scheduled',
      home_score: null,
      away_score: null,
      home_team_name: 'Arsenal',
      away_team_name: 'Bayern Munich',
      home: { id: 'arsenal', slug: 'arsenal', name: 'Arsenal', crest_url: null },
      away: {
        id: 'bayern-munich',
        slug: 'bayern-munich',
        name: 'Bayern Munich',
        crest_url: null,
      },
    },
  ],
}
