import type { StandingsOverMatchdaysConfig } from './index'

export const sample: StandingsOverMatchdaysConfig = {
  type: 'fs:standings-over-matchdays',
  competitionLabel: 'Premier League · 2025/26 (sample)',
  totalMatchdays: 12,
  lanes: [
    {
      team_id: 'man-utd',
      team_name: 'Manchester United',
      team_code: 'MUN',
      color: '#DA291C',
      points: [
        { matchday: 1, position: 6 },
        { matchday: 2, position: 7 },
        { matchday: 3, position: 6 },
        { matchday: 4, position: 5 },
        { matchday: 5, position: 5 },
        { matchday: 6, position: 4 },
        { matchday: 7, position: 4 },
        { matchday: 8, position: 4 },
        { matchday: 9, position: 3 },
        { matchday: 10, position: 3 },
        { matchday: 11, position: 3 },
        { matchday: 12, position: 3 },
      ],
    },
    {
      team_id: 'arsenal',
      team_name: 'Arsenal',
      team_code: 'ARS',
      color: '#EF0107',
      points: [
        { matchday: 1, position: 1 },
        { matchday: 2, position: 1 },
        { matchday: 3, position: 1 },
        { matchday: 4, position: 1 },
        { matchday: 5, position: 2 },
        { matchday: 6, position: 1 },
        { matchday: 7, position: 1 },
        { matchday: 8, position: 1 },
        { matchday: 9, position: 1 },
        { matchday: 10, position: 1 },
        { matchday: 11, position: 1 },
        { matchday: 12, position: 1 },
      ],
    },
    {
      team_id: 'man-city',
      team_name: 'Manchester City',
      team_code: 'MCI',
      color: '#6CABDD',
      points: [
        { matchday: 1, position: 2 },
        { matchday: 2, position: 2 },
        { matchday: 3, position: 3 },
        { matchday: 4, position: 2 },
        { matchday: 5, position: 1 },
        { matchday: 6, position: 2 },
        { matchday: 7, position: 2 },
        { matchday: 8, position: 2 },
        { matchday: 9, position: 2 },
        { matchday: 10, position: 2 },
        { matchday: 11, position: 2 },
        { matchday: 12, position: 2 },
      ],
    },
    {
      team_id: 'liverpool',
      team_name: 'Liverpool',
      team_code: 'LIV',
      color: '#C8102E',
      points: [
        { matchday: 1, position: 3 },
        { matchday: 2, position: 3 },
        { matchday: 3, position: 2 },
        { matchday: 4, position: 4 },
        { matchday: 5, position: 4 },
        { matchday: 6, position: 3 },
        { matchday: 7, position: 3 },
        { matchday: 8, position: 3 },
        { matchday: 9, position: 4 },
        { matchday: 10, position: 4 },
        { matchday: 11, position: 4 },
        { matchday: 12, position: 4 },
      ],
    },
  ],
}
