-- National teams as taggable entities — all 211 FIFA member associations.
--
-- Article tagging only links names that resolve to an `entities` row, and no
-- national team was ever seeded: seed.ts builds teams from football-data.org
-- competition rosters, and the WC26 data lives in `fifa_wc26_teams`, which the
-- resolver never reads. So every international story logged
-- `[entity-miss] team=Argentina` (and Spain, Brazil, England, Bolivia, …) and
-- shipped untagged — no chip, no follow-graph link, bare "No image" card.
--
-- Rows mirror apps/footshorts/shared/src/nationalTeams.ts, which also feeds
-- the resolver's aliases ("Korea Republic", "Côte d'Ivoire", "USA", …) and the
-- `backfill:entity-tags -- --national-teams` mode. The worker test
-- nationalTeams.test.ts fails if this file and that list drift apart.
--
-- `fifa_code` is FIFA's trigram — the same key as fifa_wc26_teams.code and
-- wc26_squads.country_code — and marks a team row as a national side (clubs
-- leave it null). `country` is the team name, matching how football-data.org
-- labels clubs' `area` ("England", "Spain"). league_slug stays null: national
-- teams have no domestic league, same as the continental-only clubs.
--
-- crest_url is a flagcdn.com PNG; after applying, run
--   npm run backfill:colors
-- in apps/footshorts/worker to sample primary_color from the flags (only
-- fills nulls), then
--   npm run backfill:entity-tags -- --national-teams
-- to tag recent articles whose headline names a national team.

alter table entities
  add column if not exists fifa_code text;

create unique index if not exists idx_entities_fifa_code
  on entities (fifa_code)
  where fifa_code is not null;

insert into entities (type, slug, name, country, fifa_code, crest_url)
select 'team', v.slug, v.name, v.name, v.fifa_code, v.crest_url
from (values
  ('afghanistan', 'Afghanistan', 'AFG', 'https://flagcdn.com/w320/af.png'),
  ('australia', 'Australia', 'AUS', 'https://flagcdn.com/w320/au.png'),
  ('bahrain', 'Bahrain', 'BHR', 'https://flagcdn.com/w320/bh.png'),
  ('bangladesh', 'Bangladesh', 'BAN', 'https://flagcdn.com/w320/bd.png'),
  ('bhutan', 'Bhutan', 'BHU', 'https://flagcdn.com/w320/bt.png'),
  ('brunei', 'Brunei', 'BRU', 'https://flagcdn.com/w320/bn.png'),
  ('cambodia', 'Cambodia', 'CAM', 'https://flagcdn.com/w320/kh.png'),
  ('china', 'China', 'CHN', 'https://flagcdn.com/w320/cn.png'),
  ('chinese-taipei', 'Chinese Taipei', 'TPE', 'https://flagcdn.com/w320/tw.png'),
  ('guam', 'Guam', 'GUM', 'https://flagcdn.com/w320/gu.png'),
  ('hong-kong', 'Hong Kong', 'HKG', 'https://flagcdn.com/w320/hk.png'),
  ('india', 'India', 'IND', 'https://flagcdn.com/w320/in.png'),
  ('indonesia', 'Indonesia', 'IDN', 'https://flagcdn.com/w320/id.png'),
  ('iran', 'Iran', 'IRN', 'https://flagcdn.com/w320/ir.png'),
  ('iraq', 'Iraq', 'IRQ', 'https://flagcdn.com/w320/iq.png'),
  ('japan', 'Japan', 'JPN', 'https://flagcdn.com/w320/jp.png'),
  ('jordan', 'Jordan', 'JOR', 'https://flagcdn.com/w320/jo.png'),
  ('kuwait', 'Kuwait', 'KUW', 'https://flagcdn.com/w320/kw.png'),
  ('kyrgyzstan', 'Kyrgyzstan', 'KGZ', 'https://flagcdn.com/w320/kg.png'),
  ('laos', 'Laos', 'LAO', 'https://flagcdn.com/w320/la.png'),
  ('lebanon', 'Lebanon', 'LBN', 'https://flagcdn.com/w320/lb.png'),
  ('macau', 'Macau', 'MAC', 'https://flagcdn.com/w320/mo.png'),
  ('malaysia', 'Malaysia', 'MAS', 'https://flagcdn.com/w320/my.png'),
  ('maldives', 'Maldives', 'MDV', 'https://flagcdn.com/w320/mv.png'),
  ('mongolia', 'Mongolia', 'MNG', 'https://flagcdn.com/w320/mn.png'),
  ('myanmar', 'Myanmar', 'MYA', 'https://flagcdn.com/w320/mm.png'),
  ('nepal', 'Nepal', 'NEP', 'https://flagcdn.com/w320/np.png'),
  ('north-korea', 'North Korea', 'PRK', 'https://flagcdn.com/w320/kp.png'),
  ('oman', 'Oman', 'OMA', 'https://flagcdn.com/w320/om.png'),
  ('pakistan', 'Pakistan', 'PAK', 'https://flagcdn.com/w320/pk.png'),
  ('palestine', 'Palestine', 'PLE', 'https://flagcdn.com/w320/ps.png'),
  ('philippines', 'Philippines', 'PHI', 'https://flagcdn.com/w320/ph.png'),
  ('qatar', 'Qatar', 'QAT', 'https://flagcdn.com/w320/qa.png'),
  ('saudi-arabia', 'Saudi Arabia', 'KSA', 'https://flagcdn.com/w320/sa.png'),
  ('singapore', 'Singapore', 'SGP', 'https://flagcdn.com/w320/sg.png'),
  ('south-korea', 'South Korea', 'KOR', 'https://flagcdn.com/w320/kr.png'),
  ('sri-lanka', 'Sri Lanka', 'SRI', 'https://flagcdn.com/w320/lk.png'),
  ('syria', 'Syria', 'SYR', 'https://flagcdn.com/w320/sy.png'),
  ('tajikistan', 'Tajikistan', 'TJK', 'https://flagcdn.com/w320/tj.png'),
  ('thailand', 'Thailand', 'THA', 'https://flagcdn.com/w320/th.png'),
  ('timor-leste', 'Timor-Leste', 'TLS', 'https://flagcdn.com/w320/tl.png'),
  ('turkmenistan', 'Turkmenistan', 'TKM', 'https://flagcdn.com/w320/tm.png'),
  ('united-arab-emirates', 'United Arab Emirates', 'UAE', 'https://flagcdn.com/w320/ae.png'),
  ('uzbekistan', 'Uzbekistan', 'UZB', 'https://flagcdn.com/w320/uz.png'),
  ('vietnam', 'Vietnam', 'VIE', 'https://flagcdn.com/w320/vn.png'),
  ('yemen', 'Yemen', 'YEM', 'https://flagcdn.com/w320/ye.png'),
  ('algeria', 'Algeria', 'ALG', 'https://flagcdn.com/w320/dz.png'),
  ('angola', 'Angola', 'ANG', 'https://flagcdn.com/w320/ao.png'),
  ('benin', 'Benin', 'BEN', 'https://flagcdn.com/w320/bj.png'),
  ('botswana', 'Botswana', 'BOT', 'https://flagcdn.com/w320/bw.png'),
  ('burkina-faso', 'Burkina Faso', 'BFA', 'https://flagcdn.com/w320/bf.png'),
  ('burundi', 'Burundi', 'BDI', 'https://flagcdn.com/w320/bi.png'),
  ('cameroon', 'Cameroon', 'CMR', 'https://flagcdn.com/w320/cm.png'),
  ('cape-verde', 'Cape Verde', 'CPV', 'https://flagcdn.com/w320/cv.png'),
  ('central-african-republic', 'Central African Republic', 'CTA', 'https://flagcdn.com/w320/cf.png'),
  ('chad', 'Chad', 'CHA', 'https://flagcdn.com/w320/td.png'),
  ('comoros', 'Comoros', 'COM', 'https://flagcdn.com/w320/km.png'),
  ('congo', 'Congo', 'CGO', 'https://flagcdn.com/w320/cg.png'),
  ('dr-congo', 'DR Congo', 'COD', 'https://flagcdn.com/w320/cd.png'),
  ('djibouti', 'Djibouti', 'DJI', 'https://flagcdn.com/w320/dj.png'),
  ('egypt', 'Egypt', 'EGY', 'https://flagcdn.com/w320/eg.png'),
  ('equatorial-guinea', 'Equatorial Guinea', 'EQG', 'https://flagcdn.com/w320/gq.png'),
  ('eritrea', 'Eritrea', 'ERI', 'https://flagcdn.com/w320/er.png'),
  ('eswatini', 'Eswatini', 'SWZ', 'https://flagcdn.com/w320/sz.png'),
  ('ethiopia', 'Ethiopia', 'ETH', 'https://flagcdn.com/w320/et.png'),
  ('gabon', 'Gabon', 'GAB', 'https://flagcdn.com/w320/ga.png'),
  ('gambia', 'Gambia', 'GAM', 'https://flagcdn.com/w320/gm.png'),
  ('ghana', 'Ghana', 'GHA', 'https://flagcdn.com/w320/gh.png'),
  ('guinea', 'Guinea', 'GUI', 'https://flagcdn.com/w320/gn.png'),
  ('guinea-bissau', 'Guinea-Bissau', 'GNB', 'https://flagcdn.com/w320/gw.png'),
  ('ivory-coast', 'Ivory Coast', 'CIV', 'https://flagcdn.com/w320/ci.png'),
  ('kenya', 'Kenya', 'KEN', 'https://flagcdn.com/w320/ke.png'),
  ('lesotho', 'Lesotho', 'LES', 'https://flagcdn.com/w320/ls.png'),
  ('liberia', 'Liberia', 'LBR', 'https://flagcdn.com/w320/lr.png'),
  ('libya', 'Libya', 'LBY', 'https://flagcdn.com/w320/ly.png'),
  ('madagascar', 'Madagascar', 'MAD', 'https://flagcdn.com/w320/mg.png'),
  ('malawi', 'Malawi', 'MWI', 'https://flagcdn.com/w320/mw.png'),
  ('mali', 'Mali', 'MLI', 'https://flagcdn.com/w320/ml.png'),
  ('mauritania', 'Mauritania', 'MTN', 'https://flagcdn.com/w320/mr.png'),
  ('mauritius', 'Mauritius', 'MRI', 'https://flagcdn.com/w320/mu.png'),
  ('morocco', 'Morocco', 'MAR', 'https://flagcdn.com/w320/ma.png'),
  ('mozambique', 'Mozambique', 'MOZ', 'https://flagcdn.com/w320/mz.png'),
  ('namibia', 'Namibia', 'NAM', 'https://flagcdn.com/w320/na.png'),
  ('niger', 'Niger', 'NIG', 'https://flagcdn.com/w320/ne.png'),
  ('nigeria', 'Nigeria', 'NGA', 'https://flagcdn.com/w320/ng.png'),
  ('rwanda', 'Rwanda', 'RWA', 'https://flagcdn.com/w320/rw.png'),
  ('sao-tome-and-principe', 'São Tomé and Príncipe', 'STP', 'https://flagcdn.com/w320/st.png'),
  ('senegal', 'Senegal', 'SEN', 'https://flagcdn.com/w320/sn.png'),
  ('seychelles', 'Seychelles', 'SEY', 'https://flagcdn.com/w320/sc.png'),
  ('sierra-leone', 'Sierra Leone', 'SLE', 'https://flagcdn.com/w320/sl.png'),
  ('somalia', 'Somalia', 'SOM', 'https://flagcdn.com/w320/so.png'),
  ('south-africa', 'South Africa', 'RSA', 'https://flagcdn.com/w320/za.png'),
  ('south-sudan', 'South Sudan', 'SSD', 'https://flagcdn.com/w320/ss.png'),
  ('sudan', 'Sudan', 'SDN', 'https://flagcdn.com/w320/sd.png'),
  ('tanzania', 'Tanzania', 'TAN', 'https://flagcdn.com/w320/tz.png'),
  ('togo', 'Togo', 'TOG', 'https://flagcdn.com/w320/tg.png'),
  ('tunisia', 'Tunisia', 'TUN', 'https://flagcdn.com/w320/tn.png'),
  ('uganda', 'Uganda', 'UGA', 'https://flagcdn.com/w320/ug.png'),
  ('zambia', 'Zambia', 'ZAM', 'https://flagcdn.com/w320/zm.png'),
  ('zimbabwe', 'Zimbabwe', 'ZIM', 'https://flagcdn.com/w320/zw.png'),
  ('anguilla', 'Anguilla', 'AIA', 'https://flagcdn.com/w320/ai.png'),
  ('antigua-and-barbuda', 'Antigua and Barbuda', 'ATG', 'https://flagcdn.com/w320/ag.png'),
  ('aruba', 'Aruba', 'ARU', 'https://flagcdn.com/w320/aw.png'),
  ('bahamas', 'Bahamas', 'BAH', 'https://flagcdn.com/w320/bs.png'),
  ('barbados', 'Barbados', 'BRB', 'https://flagcdn.com/w320/bb.png'),
  ('belize', 'Belize', 'BLZ', 'https://flagcdn.com/w320/bz.png'),
  ('bermuda', 'Bermuda', 'BER', 'https://flagcdn.com/w320/bm.png'),
  ('british-virgin-islands', 'British Virgin Islands', 'VGB', 'https://flagcdn.com/w320/vg.png'),
  ('canada', 'Canada', 'CAN', 'https://flagcdn.com/w320/ca.png'),
  ('cayman-islands', 'Cayman Islands', 'CAY', 'https://flagcdn.com/w320/ky.png'),
  ('costa-rica', 'Costa Rica', 'CRC', 'https://flagcdn.com/w320/cr.png'),
  ('cuba', 'Cuba', 'CUB', 'https://flagcdn.com/w320/cu.png'),
  ('curacao', 'Curaçao', 'CUW', 'https://flagcdn.com/w320/cw.png'),
  ('dominica', 'Dominica', 'DMA', 'https://flagcdn.com/w320/dm.png'),
  ('dominican-republic', 'Dominican Republic', 'DOM', 'https://flagcdn.com/w320/do.png'),
  ('el-salvador', 'El Salvador', 'SLV', 'https://flagcdn.com/w320/sv.png'),
  ('grenada', 'Grenada', 'GRN', 'https://flagcdn.com/w320/gd.png'),
  ('guatemala', 'Guatemala', 'GUA', 'https://flagcdn.com/w320/gt.png'),
  ('guyana', 'Guyana', 'GUY', 'https://flagcdn.com/w320/gy.png'),
  ('haiti', 'Haiti', 'HAI', 'https://flagcdn.com/w320/ht.png'),
  ('honduras', 'Honduras', 'HON', 'https://flagcdn.com/w320/hn.png'),
  ('jamaica', 'Jamaica', 'JAM', 'https://flagcdn.com/w320/jm.png'),
  ('mexico', 'Mexico', 'MEX', 'https://flagcdn.com/w320/mx.png'),
  ('montserrat', 'Montserrat', 'MSR', 'https://flagcdn.com/w320/ms.png'),
  ('nicaragua', 'Nicaragua', 'NCA', 'https://flagcdn.com/w320/ni.png'),
  ('panama', 'Panama', 'PAN', 'https://flagcdn.com/w320/pa.png'),
  ('puerto-rico', 'Puerto Rico', 'PUR', 'https://flagcdn.com/w320/pr.png'),
  ('saint-kitts-and-nevis', 'Saint Kitts and Nevis', 'SKN', 'https://flagcdn.com/w320/kn.png'),
  ('saint-lucia', 'Saint Lucia', 'LCA', 'https://flagcdn.com/w320/lc.png'),
  ('saint-vincent-and-the-grenadines', 'Saint Vincent and the Grenadines', 'VIN', 'https://flagcdn.com/w320/vc.png'),
  ('suriname', 'Suriname', 'SUR', 'https://flagcdn.com/w320/sr.png'),
  ('trinidad-and-tobago', 'Trinidad and Tobago', 'TRI', 'https://flagcdn.com/w320/tt.png'),
  ('turks-and-caicos-islands', 'Turks and Caicos Islands', 'TCA', 'https://flagcdn.com/w320/tc.png'),
  ('united-states', 'United States', 'USA', 'https://flagcdn.com/w320/us.png'),
  ('us-virgin-islands', 'US Virgin Islands', 'VIR', 'https://flagcdn.com/w320/vi.png'),
  ('argentina', 'Argentina', 'ARG', 'https://flagcdn.com/w320/ar.png'),
  ('bolivia', 'Bolivia', 'BOL', 'https://flagcdn.com/w320/bo.png'),
  ('brazil', 'Brazil', 'BRA', 'https://flagcdn.com/w320/br.png'),
  ('chile', 'Chile', 'CHI', 'https://flagcdn.com/w320/cl.png'),
  ('colombia', 'Colombia', 'COL', 'https://flagcdn.com/w320/co.png'),
  ('ecuador', 'Ecuador', 'ECU', 'https://flagcdn.com/w320/ec.png'),
  ('paraguay', 'Paraguay', 'PAR', 'https://flagcdn.com/w320/py.png'),
  ('peru', 'Peru', 'PER', 'https://flagcdn.com/w320/pe.png'),
  ('uruguay', 'Uruguay', 'URU', 'https://flagcdn.com/w320/uy.png'),
  ('venezuela', 'Venezuela', 'VEN', 'https://flagcdn.com/w320/ve.png'),
  ('american-samoa', 'American Samoa', 'ASA', 'https://flagcdn.com/w320/as.png'),
  ('cook-islands', 'Cook Islands', 'COK', 'https://flagcdn.com/w320/ck.png'),
  ('fiji', 'Fiji', 'FIJ', 'https://flagcdn.com/w320/fj.png'),
  ('new-caledonia', 'New Caledonia', 'NCL', 'https://flagcdn.com/w320/nc.png'),
  ('new-zealand', 'New Zealand', 'NZL', 'https://flagcdn.com/w320/nz.png'),
  ('papua-new-guinea', 'Papua New Guinea', 'PNG', 'https://flagcdn.com/w320/pg.png'),
  ('samoa', 'Samoa', 'SAM', 'https://flagcdn.com/w320/ws.png'),
  ('solomon-islands', 'Solomon Islands', 'SOL', 'https://flagcdn.com/w320/sb.png'),
  ('tahiti', 'Tahiti', 'TAH', 'https://flagcdn.com/w320/pf.png'),
  ('tonga', 'Tonga', 'TGA', 'https://flagcdn.com/w320/to.png'),
  ('vanuatu', 'Vanuatu', 'VAN', 'https://flagcdn.com/w320/vu.png'),
  ('albania', 'Albania', 'ALB', 'https://flagcdn.com/w320/al.png'),
  ('andorra', 'Andorra', 'AND', 'https://flagcdn.com/w320/ad.png'),
  ('armenia', 'Armenia', 'ARM', 'https://flagcdn.com/w320/am.png'),
  ('austria', 'Austria', 'AUT', 'https://flagcdn.com/w320/at.png'),
  ('azerbaijan', 'Azerbaijan', 'AZE', 'https://flagcdn.com/w320/az.png'),
  ('belarus', 'Belarus', 'BLR', 'https://flagcdn.com/w320/by.png'),
  ('belgium', 'Belgium', 'BEL', 'https://flagcdn.com/w320/be.png'),
  ('bosnia-and-herzegovina', 'Bosnia and Herzegovina', 'BIH', 'https://flagcdn.com/w320/ba.png'),
  ('bulgaria', 'Bulgaria', 'BUL', 'https://flagcdn.com/w320/bg.png'),
  ('croatia', 'Croatia', 'CRO', 'https://flagcdn.com/w320/hr.png'),
  ('cyprus', 'Cyprus', 'CYP', 'https://flagcdn.com/w320/cy.png'),
  ('czechia', 'Czechia', 'CZE', 'https://flagcdn.com/w320/cz.png'),
  ('denmark', 'Denmark', 'DEN', 'https://flagcdn.com/w320/dk.png'),
  ('england', 'England', 'ENG', 'https://flagcdn.com/w320/gb-eng.png'),
  ('estonia', 'Estonia', 'EST', 'https://flagcdn.com/w320/ee.png'),
  ('faroe-islands', 'Faroe Islands', 'FRO', 'https://flagcdn.com/w320/fo.png'),
  ('finland', 'Finland', 'FIN', 'https://flagcdn.com/w320/fi.png'),
  ('france', 'France', 'FRA', 'https://flagcdn.com/w320/fr.png'),
  ('georgia', 'Georgia', 'GEO', 'https://flagcdn.com/w320/ge.png'),
  ('germany', 'Germany', 'GER', 'https://flagcdn.com/w320/de.png'),
  ('gibraltar', 'Gibraltar', 'GIB', 'https://flagcdn.com/w320/gi.png'),
  ('greece', 'Greece', 'GRE', 'https://flagcdn.com/w320/gr.png'),
  ('hungary', 'Hungary', 'HUN', 'https://flagcdn.com/w320/hu.png'),
  ('iceland', 'Iceland', 'ISL', 'https://flagcdn.com/w320/is.png'),
  ('israel', 'Israel', 'ISR', 'https://flagcdn.com/w320/il.png'),
  ('italy', 'Italy', 'ITA', 'https://flagcdn.com/w320/it.png'),
  ('kazakhstan', 'Kazakhstan', 'KAZ', 'https://flagcdn.com/w320/kz.png'),
  ('kosovo', 'Kosovo', 'KVX', 'https://flagcdn.com/w320/xk.png'),
  ('latvia', 'Latvia', 'LVA', 'https://flagcdn.com/w320/lv.png'),
  ('liechtenstein', 'Liechtenstein', 'LIE', 'https://flagcdn.com/w320/li.png'),
  ('lithuania', 'Lithuania', 'LTU', 'https://flagcdn.com/w320/lt.png'),
  ('luxembourg', 'Luxembourg', 'LUX', 'https://flagcdn.com/w320/lu.png'),
  ('malta', 'Malta', 'MLT', 'https://flagcdn.com/w320/mt.png'),
  ('moldova', 'Moldova', 'MDA', 'https://flagcdn.com/w320/md.png'),
  ('montenegro', 'Montenegro', 'MNE', 'https://flagcdn.com/w320/me.png'),
  ('netherlands', 'Netherlands', 'NED', 'https://flagcdn.com/w320/nl.png'),
  ('north-macedonia', 'North Macedonia', 'MKD', 'https://flagcdn.com/w320/mk.png'),
  ('northern-ireland', 'Northern Ireland', 'NIR', 'https://flagcdn.com/w320/gb-nir.png'),
  ('norway', 'Norway', 'NOR', 'https://flagcdn.com/w320/no.png'),
  ('poland', 'Poland', 'POL', 'https://flagcdn.com/w320/pl.png'),
  ('portugal', 'Portugal', 'POR', 'https://flagcdn.com/w320/pt.png'),
  ('republic-of-ireland', 'Republic of Ireland', 'IRL', 'https://flagcdn.com/w320/ie.png'),
  ('romania', 'Romania', 'ROU', 'https://flagcdn.com/w320/ro.png'),
  ('russia', 'Russia', 'RUS', 'https://flagcdn.com/w320/ru.png'),
  ('san-marino', 'San Marino', 'SMR', 'https://flagcdn.com/w320/sm.png'),
  ('scotland', 'Scotland', 'SCO', 'https://flagcdn.com/w320/gb-sct.png'),
  ('serbia', 'Serbia', 'SRB', 'https://flagcdn.com/w320/rs.png'),
  ('slovakia', 'Slovakia', 'SVK', 'https://flagcdn.com/w320/sk.png'),
  ('slovenia', 'Slovenia', 'SVN', 'https://flagcdn.com/w320/si.png'),
  ('spain', 'Spain', 'ESP', 'https://flagcdn.com/w320/es.png'),
  ('sweden', 'Sweden', 'SWE', 'https://flagcdn.com/w320/se.png'),
  ('switzerland', 'Switzerland', 'SUI', 'https://flagcdn.com/w320/ch.png'),
  ('turkey', 'Turkey', 'TUR', 'https://flagcdn.com/w320/tr.png'),
  ('ukraine', 'Ukraine', 'UKR', 'https://flagcdn.com/w320/ua.png'),
  ('wales', 'Wales', 'WAL', 'https://flagcdn.com/w320/gb-wls.png')
) as v(slug, name, fifa_code, crest_url)
-- A row already at this slug can only be a national team a past seed got to
-- first (no domestic club is named after a country); claim it rather than
-- duplicate it, and keep any crest/country it already has. The league_slug
-- guard leaves a domestic club untouched should one ever share the slug.
on conflict (type, slug) do update
  set fifa_code = excluded.fifa_code,
      country   = coalesce(entities.country, excluded.country),
      crest_url = coalesce(entities.crest_url, excluded.crest_url)
  where entities.league_slug is null;
