/**
 * Server-side readers for the travel app's trip sidecar files:
 *
 *   content/stories/<slug>.trip.yaml   — canonical structured itinerary
 *                                        (generated by scripts/travel/import-pro-trip.ts)
 *   content/stories/<slug>.media.yaml  — media manifest (written by
 *                                        scripts/travel/prepare-media.ts, hand-editable)
 *
 * `readTrip` merges the manifest onto the itinerary so every stop (and day)
 * carries its media — the journey map view renders straight from this shape
 * with zero per-view config.
 *
 * Coordinates throughout are **[lng, lat]** (Mapbox order).
 */

import fs from 'node:fs'
import path from 'node:path'
import YAML from 'yaml'
import { buildTripData } from '@vismay/content-source/travelTrips'
import type {
  StopMedia,
  TripAirport,
  TripData,
  TripDay,
  TripStay,
  TripStop,
} from '@vismay/content-source/travelTrips'

// Canonical itinerary types live in content-source (shared with admin + the
// render surface, which read the DB-mirrored itinerary); re-export so the
// journey components keep importing from '@/lib/trips'.
export type { StopMedia, TripAirport, TripData, TripDay, TripStay, TripStop }

const STORIES_DIR =
  process.env.STORY_CONTENT_DIR || path.join(process.cwd(), 'content/stories')

interface MediaManifestEntry {
  file?: string
  kind?: string
  day?: number | null
  stop?: string | null
  caption?: string
  takenAt?: string
}

function readYamlIfExists<T>(p: string): T | null {
  if (!fs.existsSync(p)) return null
  try {
    return YAML.parse(fs.readFileSync(p, 'utf8')) as T
  } catch (e) {
    console.warn(`[travel] failed to parse ${p}: ${e instanceof Error ? e.message : e}`)
    return null
  }
}

export function listTripSlugs(): string[] {
  if (!fs.existsSync(STORIES_DIR)) return []
  return fs
    .readdirSync(STORIES_DIR)
    .filter((f) => f.endsWith('.trip.yaml'))
    .map((f) => f.replace(/\.trip\.yaml$/, ''))
    .sort()
}

export function readTrip(slug: string): TripData | null {
  const trip = readTripBase(slug)
  if (!trip) return null
  attachMediaFromYaml(trip)
  return trip
}

/**
 * DB-first variant for the journey view: media comes from `travel_trip_media`
 * (what /curate edits — only `selected` rows), falling back to the git YAML
 * manifest when the env is missing, the table isn't migrated/seeded, or the
 * query fails. Mirrors gate.ts's fails-open-in-dev posture.
 */
export async function readTripWithMedia(slug: string): Promise<TripData | null> {
  const trip = readTripBase(slug)
  if (!trip) return null

  if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) {
    try {
      const { listTripMedia } = await import('@vismay/content-source/travelMedia')
      const rows = (await listTripMedia(slug)).filter((r) => r.selected)
      if (rows.length > 0) {
        attachRows(
          trip,
          rows.map((r) => ({
            file: r.file,
            kind: r.kind,
            day: r.day,
            stop: r.stop,
            caption: r.caption ?? undefined,
            takenAt: r.taken_at ?? undefined,
          }))
        )
        return trip
      }
      console.warn(`[travel] travel_trip_media empty for ${slug} — using YAML manifest`)
    } catch (e) {
      console.warn(`[travel] media DB read failed for ${slug}, using YAML manifest:`, e)
    }
  }
  attachMediaFromYaml(trip)
  return trip
}

/** `readTrip` minus the media attach — shared base for both variants. */
function readTripBase(slug: string): TripData | null {
  if (!/^[a-z0-9][a-z0-9_-]*$/.test(slug)) return null
  const raw = readYamlIfExists<Record<string, unknown>>(
    path.join(STORIES_DIR, `${slug}.trip.yaml`)
  )
  if (!raw) return null
  return buildTripData(slug, raw)
}

function attachMediaFromYaml(trip: TripData): void {
  const manifest = readYamlIfExists<{ media?: MediaManifestEntry[] }>(
    path.join(STORIES_DIR, `${trip.slug}.media.yaml`)
  )
  if (!manifest?.media) return
  attachRows(trip, manifest.media)
}

function attachRows(trip: TripData, entries: MediaManifestEntry[]): void {
  const stopsBySlug = new Map<string, TripStop>()
  for (const day of trip.days) for (const stop of day.stops) stopsBySlug.set(stop.slug, stop)
  const daysByN = new Map<number, TripDay>()
  for (const day of trip.days) if (day.n != null) daysByN.set(day.n, day)

  for (const entry of entries) {
    if (!entry.file) continue
    const media: StopMedia = {
      file: entry.file,
      ref: `assets://${trip.slug}/${entry.file}`,
      kind: entry.kind === 'video' ? 'video' : 'image',
      caption: entry.caption,
      takenAt: entry.takenAt,
    }
    const stop = entry.stop ? stopsBySlug.get(entry.stop) : undefined
    if (stop) {
      stop.media.push(media)
      continue
    }
    const day = entry.day != null ? daysByN.get(entry.day) : undefined
    if (day) day.media.push(media)
    // Entries with neither a resolvable stop nor day are unassigned — skip
    // here; /curate is where they surface.
  }
}
