import type { StandingsTableConfig } from './index'

export const sample: StandingsTableConfig = {
  type: 'fs:standings-table',
  rows: [
    {
      competition_slug: 'prem',
      season: '2025',
      team_id: 'arsenal',
      position: 1,
      played: 12,
      won: 9,
      draw: 2,
      lost: 1,
      goals_for: 26,
      goals_against: 9,
      goal_difference: 17,
      points: 29,
      form: 'WWDWW',
      team: { id: 'arsenal', slug: 'arsenal', name: 'Arsenal', crest_url: null },
    },
    {
      competition_slug: 'prem',
      season: '2025',
      team_id: 'liverpool',
      position: 2,
      played: 12,
      won: 8,
      draw: 3,
      lost: 1,
      goals_for: 24,
      goals_against: 11,
      goal_difference: 13,
      points: 27,
      form: 'WWDDW',
      team: { id: 'liverpool', slug: 'liverpool', name: 'Liverpool', crest_url: null },
    },
    {
      competition_slug: 'prem',
      season: '2025',
      team_id: 'man-city',
      position: 3,
      played: 12,
      won: 8,
      draw: 2,
      lost: 2,
      goals_for: 23,
      goals_against: 10,
      goal_difference: 13,
      points: 26,
      form: 'LWWDW',
      team: { id: 'man-city', slug: 'man-city', name: 'Manchester City', crest_url: null },
    },
    {
      competition_slug: 'prem',
      season: '2025',
      team_id: 'chelsea',
      position: 4,
      played: 12,
      won: 7,
      draw: 3,
      lost: 2,
      goals_for: 20,
      goals_against: 12,
      goal_difference: 8,
      points: 24,
      form: 'WWLDW',
      team: { id: 'chelsea', slug: 'chelsea', name: 'Chelsea', crest_url: null },
    },
    {
      competition_slug: 'prem',
      season: '2025',
      team_id: 'tottenham',
      position: 5,
      played: 12,
      won: 6,
      draw: 4,
      lost: 2,
      goals_for: 19,
      goals_against: 13,
      goal_difference: 6,
      points: 22,
      form: 'DDWWW',
      team: { id: 'tottenham', slug: 'tottenham', name: 'Tottenham', crest_url: null },
    },
  ],
}
