import type { TacticsBoardConfig } from './index'

/**
 * Catalog fixture — the canonical "Carrick build-up" phase from
 * footshorts-data/content/phases/carrick-buildup-1.json. A 4-2-3-1 playing out
 * from the back: RCB → RDM → AM through the lines, RB overlapping, LW dropping
 * to combine, with a central overload zone.
 */
export const sample: TacticsBoardConfig = {
  type: 'fs:tactics-board',
  title: 'Building from the back',
  homeLabel: 'Middlesbrough',
  awayLabel: 'Man Utd',
  homeColor: '#d2122e',
  awayColor: '#2f6df6',
  loop: true,
  phase: {
    phaseId: 'carrick-buildup-1',
    formation: '4-2-3-1',
    durationSec: 4,
    frames: [
      {
        t: 0,
        ball: { x: 18, y: 50 },
        players: [
          { id: 'GK', x: 8, y: 50, team: 'home' },
          { id: 'RB', x: 22, y: 82, team: 'home' },
          { id: 'RCB', x: 18, y: 60, team: 'home' },
          { id: 'LCB', x: 18, y: 40, team: 'home' },
          { id: 'LB', x: 22, y: 18, team: 'home' },
          { id: 'RDM', x: 35, y: 58, team: 'home' },
          { id: 'LDM', x: 35, y: 42, team: 'home' },
          { id: 'RW', x: 60, y: 78, team: 'home' },
          { id: 'AM', x: 50, y: 50, team: 'home' },
          { id: 'LW', x: 55, y: 30, team: 'home' },
          { id: 'ST', x: 70, y: 55, team: 'home' },
          { id: 'A_ST1', x: 65, y: 45, team: 'away' },
          { id: 'A_ST2', x: 65, y: 55, team: 'away' },
          { id: 'A_AM', x: 55, y: 50, team: 'away' },
          { id: 'A_RW', x: 50, y: 80, team: 'away' },
          { id: 'A_LW', x: 50, y: 20, team: 'away' },
          { id: 'A_RM', x: 40, y: 60, team: 'away' },
          { id: 'A_LM', x: 40, y: 40, team: 'away' },
          { id: 'A_RB', x: 25, y: 78, team: 'away' },
          { id: 'A_RCB', x: 22, y: 58, team: 'away' },
          { id: 'A_LCB', x: 22, y: 42, team: 'away' },
          { id: 'A_LB', x: 25, y: 22, team: 'away' },
        ],
      },
      {
        t: 2,
        ball: { x: 35, y: 58 },
        players: [
          { id: 'GK', x: 8, y: 50, team: 'home' },
          { id: 'RB', x: 35, y: 88, team: 'home' },
          { id: 'RCB', x: 22, y: 62, team: 'home' },
          { id: 'LCB', x: 22, y: 38, team: 'home' },
          { id: 'LB', x: 35, y: 12, team: 'home' },
          { id: 'RDM', x: 38, y: 58, team: 'home' },
          { id: 'LDM', x: 42, y: 42, team: 'home' },
          { id: 'RW', x: 65, y: 82, team: 'home' },
          { id: 'AM', x: 55, y: 48, team: 'home' },
          { id: 'LW', x: 50, y: 38, team: 'home' },
          { id: 'ST', x: 78, y: 48, team: 'home' },
          { id: 'A_ST1', x: 60, y: 45, team: 'away' },
          { id: 'A_ST2', x: 60, y: 55, team: 'away' },
          { id: 'A_AM', x: 50, y: 50, team: 'away' },
          { id: 'A_RW', x: 48, y: 80, team: 'away' },
          { id: 'A_LW', x: 48, y: 20, team: 'away' },
          { id: 'A_RM', x: 42, y: 58, team: 'away' },
          { id: 'A_LM', x: 42, y: 42, team: 'away' },
          { id: 'A_RB', x: 30, y: 78, team: 'away' },
          { id: 'A_RCB', x: 28, y: 58, team: 'away' },
          { id: 'A_LCB', x: 28, y: 42, team: 'away' },
          { id: 'A_LB', x: 30, y: 22, team: 'away' },
        ],
      },
      {
        t: 4,
        ball: { x: 55, y: 48 },
        players: [
          { id: 'GK', x: 10, y: 50, team: 'home' },
          { id: 'RB', x: 48, y: 88, team: 'home' },
          { id: 'RCB', x: 28, y: 62, team: 'home' },
          { id: 'LCB', x: 28, y: 38, team: 'home' },
          { id: 'LB', x: 45, y: 10, team: 'home' },
          { id: 'RDM', x: 42, y: 55, team: 'home' },
          { id: 'LDM', x: 48, y: 42, team: 'home' },
          { id: 'RW', x: 72, y: 80, team: 'home' },
          { id: 'AM', x: 58, y: 48, team: 'home' },
          { id: 'LW', x: 55, y: 42, team: 'home' },
          { id: 'ST', x: 82, y: 42, team: 'home' },
          { id: 'A_ST1', x: 55, y: 45, team: 'away' },
          { id: 'A_ST2', x: 55, y: 55, team: 'away' },
          { id: 'A_AM', x: 48, y: 50, team: 'away' },
          { id: 'A_RW', x: 50, y: 78, team: 'away' },
          { id: 'A_LW', x: 50, y: 22, team: 'away' },
          { id: 'A_RM', x: 48, y: 58, team: 'away' },
          { id: 'A_LM', x: 48, y: 42, team: 'away' },
          { id: 'A_RB', x: 35, y: 78, team: 'away' },
          { id: 'A_RCB', x: 35, y: 58, team: 'away' },
          { id: 'A_LCB', x: 35, y: 42, team: 'away' },
          { id: 'A_LB', x: 35, y: 22, team: 'away' },
        ],
      },
    ],
    annotations: [
      { type: 'pass', from: 'RCB', to: 'RDM', at: 0.5 },
      { type: 'pass', from: 'RDM', to: 'AM', at: 2.2 },
      { type: 'run', playerId: 'RB', path: [[22, 82], [35, 88], [48, 88]], at: 0.8, duration: 3.0 },
      { type: 'run', playerId: 'LW', path: [[55, 30], [50, 38], [55, 42]], at: 1.0, duration: 2.5 },
      {
        type: 'zone',
        polygon: [[35, 35], [55, 35], [55, 65], [35, 65]],
        label: 'Central overload',
        at: 1.5,
        duration: 2.5,
      },
    ],
  },
}
