import type { RaceReplayConfig } from './index'
import { sampleFixture } from './sampleFixture'

/**
 * Catalog/SSG sample — carries a compact inline fixture (5 cars · 2 laps · 1 Hz,
 * generated by `scripts/genReplaySampleFixture.mjs`) so the preview renders the
 * full interactive replay with zero network dependency. Real stories instead
 * set `sessionRef` / `fixtureUrl`.
 */
export const sample: RaceReplayConfig = {
  type: 'f1:race-replay',
  title: 'Vismay Demo GP — opening laps',
  autoPlay: true,
  fixture: sampleFixture,
}
