/**
 * Generate the Tailwind `@source` partials from the vertical registry.
 *
 * `vizmaya-fyi` is the universal headless render surface and admin/catalog show
 * every vertical's modules, so all three must scan every vertical's source —
 * otherwise a module's package-only arbitrary class (e.g. f1 driver-standings'
 * `grid-cols-[28px_1fr_60px_40px_40px]`) gets purged and its grid collapses to
 * one column in those surfaces. That list used to be hand-copied per app and
 * silently drifted (see docs/vertical-registration-drift.md).
 *
 * This reads `VERTICALS[].tailwindSources` (the single source of truth) and
 * writes a `globals.generated.css` next to each surface's `globals.css`, which
 * imports it. Adding a vertical to the registry updates all three from one run.
 *
 * Usage:
 *   pnpm gen:sources           # write the generated partials
 *   pnpm gen:sources --check   # exit non-zero if any partial is stale (CI)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

import { VERTICALS } from '../packages/verticals/src/data.ts'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/**
 * Surfaces that render/list EVERY vertical and therefore scan all of them.
 * Each path is the directory holding the app's `globals.css` (Tailwind v4
 * resolves `@source` relative to the file the directive lives in, so the
 * generated partial must sit beside `globals.css`).
 */
const SURFACES = [
  'apps/vizmaya-fyi/app',
  'apps/admin/app',
  'apps/catalog/app',
]

const GENERATED_FILENAME = 'globals.generated.css'

/** Build the generated CSS for one surface dir, with paths rebased to it. */
function renderPartial(surfaceDir: string): string {
  const absSurfaceDir = join(repoRoot, surfaceDir)
  const lines = VERTICALS.flatMap((v) =>
    v.tailwindSources.map((glob) => {
      const rel = relative(absSurfaceDir, join(repoRoot, glob)).split(sep).join('/')
      return `@source "${rel}";`
    })
  )
  return [
    '/* AUTO-GENERATED by `pnpm gen:sources` (scripts/gen-tailwind-sources.mts).',
    '   Source of truth: packages/viz-engine/src/verticalRegistry.ts',
    '   (VERTICALS[].tailwindSources). Do not edit by hand — re-run the',
    '   generator and commit. CI fails on drift via `pnpm gen:sources --check`. */',
    ...lines,
    '',
  ].join('\n')
}

const check = process.argv.includes('--check')
let stale = 0

for (const surfaceDir of SURFACES) {
  const target = join(repoRoot, surfaceDir, GENERATED_FILENAME)
  const next = renderPartial(surfaceDir)
  let current: string | null = null
  try {
    current = readFileSync(target, 'utf8')
  } catch {
    current = null
  }
  if (current === next) {
    if (!check) console.log(`✓ up to date  ${surfaceDir}/${GENERATED_FILENAME}`)
    continue
  }
  if (check) {
    stale++
    console.error(`✗ stale       ${surfaceDir}/${GENERATED_FILENAME}`)
  } else {
    writeFileSync(target, next)
    console.log(`↻ wrote       ${surfaceDir}/${GENERATED_FILENAME}`)
  }
}

if (check && stale > 0) {
  console.error(
    `\n${stale} generated @source partial(s) are stale. Run \`pnpm gen:sources\` and commit.`
  )
  process.exit(1)
}
