'use client';

import { useQuery } from '@tanstack/react-query';
import { supabase } from './supabase';

/** One row of `daily_recaps` — generated by worker/src/recap.ts. */
export type RecapMeta = {
  recap_date: string; // YYYY-MM-DD
  scope: string; // 'all' | competition_slug
  model: string | null;
  fixture_count: number;
  article_count: number;
  generated_at: string;
};

export type Recap = RecapMeta & { markdown: string };

/** List recaps (newest first), without the markdown body. */
export function useRecapList() {
  return useQuery<RecapMeta[]>({
    queryKey: ['recap-list'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('daily_recaps')
        .select('recap_date, scope, model, fixture_count, article_count, generated_at')
        .order('recap_date', { ascending: false })
        .order('scope', { ascending: true });
      if (error) throw error;
      return (data ?? []) as RecapMeta[];
    },
  });
}

/** Fetch a single recap's markdown by (date, scope). */
export function useRecap(date: string | null, scope: string | null) {
  return useQuery<Recap | null>({
    queryKey: ['recap', date, scope],
    enabled: !!date && !!scope,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('daily_recaps')
        .select('recap_date, scope, model, fixture_count, article_count, generated_at, markdown')
        .eq('recap_date', date!)
        .eq('scope', scope!)
        .maybeSingle();
      if (error) throw error;
      return (data ?? null) as Recap | null;
    },
  });
}
