/**
 * Build the hosted format runtimes from ../formats into
 * src/formatAssets.generated.ts, which ./src/formatsApi serves at
 * <site>/formats/<file> (bundled as strings, so serving needs no file
 * tracing on Vercel):
 *
 *   story@1.js               the story runtime alone (charts, count-ups, enter)
 *   book@1.js, book@1.css    story.js + book.js; common.css + book.css
 *   board@1.js, board@1.css  likewise
 *   deck@1.js, deck@1.css    likewise
 *   examples/odyssey-*.html  the reference pages the brief links to
 *
 * Usage:
 *   pnpm --filter @vismay/html-stories gen:formats           # write it
 *   pnpm --filter @vismay/html-stories gen:formats --check   # exit 1 if stale
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const pkg = resolve(__dirname, '..')
const formatsDir = join(pkg, 'formats')
export const GENERATED_PATH = join(pkg, 'src', 'formatAssets.generated.ts')

/** Must match FORMAT_RUNTIME_MAJOR in src/formats.ts (src/formats.test.ts checks). */
const MAJOR = 1
const PAGED = ['book', 'board', 'deck'] as const

function read(file: string): string {
  return readFileSync(join(formatsDir, file), 'utf8').replace(/\r\n/g, '\n')
}

function banner(name: string): string {
  return `/* vizmaya story formats: ${name}. Source: packages/html-stories/formats. */\n`
}

/** Published path → body. */
export function buildFormatAssets(): Record<string, string> {
  const assets: Record<string, string> = {}
  const story = read('story.js')
  const common = read('common.css')
  assets[`story@${MAJOR}.js`] = banner(`story@${MAJOR}.js`) + story
  for (const f of PAGED) {
    // ';' so the format's IIFE can't be read as a call on the story runtime's
    assets[`${f}@${MAJOR}.js`] = banner(`${f}@${MAJOR}.js`) + story + '\n;' + read(`${f}.js`)
    assets[`${f}@${MAJOR}.css`] = banner(`${f}@${MAJOR}.css`) + common + '\n' + read(`${f}.css`)
  }
  for (const file of readdirSync(join(formatsDir, 'examples')).sort()) {
    if (file.endsWith('.html')) assets[`examples/${file}`] = read(join('examples', file))
  }
  return assets
}

export function renderGeneratedModule(assets: Record<string, string>): string {
  const entries = Object.entries(assets)
    .map(([path, body]) => `  ${JSON.stringify(path)}: ${JSON.stringify(body)},`)
    .join('\n')
  return `/**
 * GENERATED by scripts/gen-format-assets.mts from ../formats. Do not edit:
 * change the files there and run \`pnpm --filter @vismay/html-stories gen:formats\`.
 */

export const FORMAT_ASSETS: Record<string, string> = {
${entries}
}
`
}

function main() {
  const next = renderGeneratedModule(buildFormatAssets())
  let current = ''
  try {
    current = readFileSync(GENERATED_PATH, 'utf8')
  } catch {}
  if (process.argv.includes('--check')) {
    if (current !== next) {
      console.error('src/formatAssets.generated.ts is stale: run pnpm --filter @vismay/html-stories gen:formats')
      process.exit(1)
    }
    console.log('format assets: up to date')
    return
  }
  if (current === next) {
    console.log('format assets: unchanged')
    return
  }
  writeFileSync(GENERATED_PATH, next)
  console.log(`format assets: wrote ${GENERATED_PATH}`)
}

if (require.main === module) main()
